### TYPE YOUR NAME HERE: Conor Murray

# ISM 5136 - Data Analytics and Mining for Business

## Lab Session: Data Wrangling with Pandas

### Overview:
This lab covers operations related to reading and manipulating data with Pandas.

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. The corresponding question text for each code cell is provided above the cell.

### Submission Format:
There are two deliverables of this lab: 1) the GitHub link and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding lab submission link by the due date indicated on Canvas.

### Important: Do <u>not</u> forget to run the cells before submitting your work.

### Data Description:

There are two data sets for this lab. The 1st dataset (census2000_v2.txt) provides geographic, demographics, and economic information about the locations in the U.S. based on the Census conducted in 2000. Each object corresponds to one zip code within the U.S. The 2nd dataset (US_areaNames.txt) provides a list of zip codes within the U.S., along with the city, county, and state names.

### Questions: Please note that there are multiple steps in each question. You can run each step individually (before moving on to the next one) to make sure that your results are correct.

#### 1. Data Import
* Import the census2000_v2.txt data into a DataFrame named df1.
* Display the column names.
* Display the size (how many rows and columns).
* Display the first 10 rows.

In [1]:
import pandas as pd
df1 = pd.read_table('census2000_v2.txt')
print(df1.columns)
print(df1.shape)
df1.head(10)

Index(['RegionID', 'Longitude', 'Latitude', 'RegionDensityPercentile',
       'RegionPopulation', 'MedianHouseholdIncome', 'AverageHouseholdSize'],
      dtype='object')
(33190, 7)

,RegionID,Longitude,Latitude,RegionDensityPercentile,RegionPopulation,MedianHouseholdIncome,AverageHouseholdSize
0,601,-66.74947,18.180103,70.0,19143,9888.0,3.24
1,602,-67.18025,18.363285,83.0,42042,11384.0,3.10
2,603,-67.13422,18.448619,86.0,55592,10748.0,2.84
3,604,-67.13700,18.498987,83.0,3844,31199.0,3.00
4,606,-66.95881,18.182151,65.0,6449,9243.0,3.20
5,610,-67.13605,18.288319,79.0,28005,12629.0,3.01
6,612,-66.69880,18.449732,81.0,72865,13000.0,2.84
7,616,-66.67669,18.426748,78.0,10525,10476.0,2.97
8,617,-66.55576,18.455499,81.0,23223,11511.0,2.97
9,622,-67.16746,18.003125,69.0,8284,13634.0,2.64

#### 2. Data Checking
* Obtain the data types of columns in df1.
* Display summary statistics for all variables.
* Write down the problems you identify in the data (use comments to write them down in the code cell below).
* Double check the existence of missing values using a method.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">Possible attributes and methods to use: dtypes, describe(include='all'), isnull().sum()</span>
2. <span style="color: black; background: black; span:hover { color: white}">Problems that you should have noticed: 1) duplicates in regionID, 2) regionID is non-numeric, 3) missing values </span>

In [2]:
# RegionID is object instead of what could be a numeric, like float64
#there is a duplicate value in RegionID as we can see from the double frequency
#we can also see that the count and unique values dont match, this means we have blank values
print(df1.dtypes)
print(df1.describe(include='all'))
df1.isnull().sum()

RegionID                    object
Longitude                  float64
Latitude                   float64
RegionDensityPercentile    float64
RegionPopulation             int64
MedianHouseholdIncome      float64
AverageHouseholdSize       float64
dtype: object
       RegionID     Longitude      Latitude  RegionDensityPercentile  \
count     33190  33190.000000  33190.000000             32177.000000
unique    33178           NaN           NaN                      NaN
top        1010           NaN           NaN                      NaN
freq          2           NaN           NaN                      NaN
mean        NaN    -91.077664     38.831628                50.504149
std         NaN     15.072058      5.358824                28.863921
min         NaN   -176.636760     17.962234                 1.000000
25%         NaN    -97.218277     35.384861                26.000000
50%         NaN    -88.304135     39.462072                51.000000
75%         NaN    -80.372860     42.109246                76.000000
max         NaN    -65.292580     71.299525               100.000000

        RegionPopulation  MedianHouseholdIncome  AverageHouseholdSize
count       33190.000000           33173.000000          33190.000000
unique               NaN                    NaN                   NaN
top                  NaN                    NaN                   NaN
freq                 NaN                    NaN                   NaN
mean         8597.913980           38251.266783              2.500703
std         12978.511224           17469.495624              0.595654
min             0.000000               0.000000              0.000000
25%           656.000000           28906.000000              2.360000
50%          2515.000000           35765.000000              2.550000
75%         11171.750000           45240.000000              2.740000
max        144024.000000          200001.000000              8.490000

RegionID                      0
Longitude                     0
Latitude                      0
RegionDensityPercentile    1013
RegionPopulation              0
MedianHouseholdIncome        17
AverageHouseholdSize          0
dtype: int64

#### 3. Data Cleaning
* Remove observations with duplicated RegionID (keep one, remove rest).
* Remove observations with non-numeric RegionID values (RegionID is the zip code, which should have been numeric. A non-numeric value indicates a problem with the entry).
* Handle missing values in two different ways:
<ol>
<li>Remove observations with missing values in RegionDensityPercentile.</li>
<li>Impute missing values in the MedianHouseholdIncome columns with the average of MedianHouseholdIncome.</li>
</ol>
* After the steps above have been completed, display the summary statistics one more time.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">Possible methods to use: drop_duplicates(), isnumeric(), dropna(), fillna(), mean()</span>
2. <span style="color: black; background: black; span:hover { color: white}">You can use "inplace=True" parameter inside most method inputs to overwrite the existing dataframe</span>
3. <span style="color: black; background: black; span:hover { color: white}">One way of imputing missing values: df1['MedianHouseholdIncome'].fillna(df1['MedianHouseholdIncome'].mean(),inplace=True) </span>

In [3]:
df1 = df1.drop_duplicates('RegionID')
df1 = df1[df1['RegionID'].astype(str).str.isnumeric()]
df1 = df1.dropna(subset=['RegionDensityPercentile'])
df1['MedianHouseholdIncome'].fillna(df1['MedianHouseholdIncome'].mean())
df1.describe(include='all')

,RegionID,Longitude,Latitude,RegionDensityPercentile,RegionPopulation,MedianHouseholdIncome,AverageHouseholdSize
count,31951,31951.000000,31951.000000,31951.000000,31951.000000,31936.000000,31951.000000
unique,31951,NaN,NaN,NaN,NaN,NaN,NaN
top,601,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,-91.044544,38.851462,50.826922,8925.830490,39502.877192,2.580923
std,NaN,15.028875,5.347606,28.683142,13114.560356,16321.490931,0.397325
min,NaN,-176.636760,17.964529,1.000000,1.000000,0.000000,0.000000
25%,NaN,-97.161550,35.415903,26.000000,776.000000,29685.500000,2.390000
50%,NaN,-88.304990,39.480856,51.000000,2762.000000,36175.500000,2.560000
75%,NaN,-80.395460,42.113861,76.000000,11867.000000,45667.000000,2.750000
max,NaN,-65.292580,71.299525,100.000000,144024.000000,200001.000000,8.490000

#### 4. 2nd Dataset Import
* Try importing the US_areaNames.txt data into a DataFrame named df2. You should notice a problem.
* The issue is that the column names are missing from this dataset. Below are the names and short descriptions of columns obtained from the source repository.
* Re-import the data using column names given below.
* Display the column names.
* Display the size (how many rows and columns).
* Obtain summary statistics
* Display the first 10 rows.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">To import data with column names, first create a list of column names and then use the "names" parameter within the read method and point it to the list.</span>


##### Data Description:
country code      : iso country code, 2 characters <br>
postal code       : varchar(20) <br>
place name        : varchar(180) <br>
admin name1       : 1. order subdivision (state) varchar(100) <br>
admin code1       : 1. order subdivision (state) varchar(20) <br>
admin name2       : 2. order subdivision (county/province) varchar(100) <br>
admin code2       : 2. order subdivision (county/province) varchar(20) <br>
admin name3       : 3. order subdivision (community) varchar(100) <br>
admin code3       : 3. order subdivision (community) varchar(20) <br>
latitude          : estimated latitude (wgs84) <br>
longitude         : estimated longitude (wgs84) <br>
accuracy          : accuracy of lat/lng from 1=estimated to 6=centroid

In [7]:
df2 = pd.read_table('US_areaNames.txt')
col_names = ['country code', 'postal code', 'place name', 'admin name1', 'admin code1', 'admin name2', 'admin code2', 'admin name3', 'admin code3', 'latitude', 'longitude', 'accuracy']
df2 = pd.read_table('US_areaNames.txt', names=col_names)
print(df2.columns)
print(df2.shape)
print(df2.head(10))
df2.describe(include='all')

Index(['country code', 'postal code', 'place name', 'admin name1',
       'admin code1', 'admin name2', 'admin code2', 'admin name3',
       'admin code3', 'latitude', 'longitude', 'accuracy'],
      dtype='object')
(43628, 12)
  country code  postal code           place name admin name1 admin code1  \
0           US        34050                  FPO         NaN          AA
1           US        34034                  APO         NaN          AA
2           US        99553               Akutan      Alaska          AK
3           US        99571             Cold Bay      Alaska          AK
4           US        99583           False Pass      Alaska          AK
5           US        99612            King Cove      Alaska          AK
6           US        99661           Sand Point      Alaska          AK
7           US        99546                 Adak      Alaska          AK
8           US        99547                 Atka      Alaska          AK
9           US        99591  Saint George Island      Alaska          AK

           admin name2  admin code2  admin name3  admin code3  latitude  \
0                 Erie         29.0          NaN          NaN   41.0375
1               Dillon         33.0          NaN          NaN   33.0364
2       Aleutians East         13.0          NaN          NaN   54.1430
3       Aleutians East         13.0          NaN          NaN   55.3976
4       Aleutians East         13.0          NaN          NaN   54.8410
5       Aleutians East         13.0          NaN          NaN   55.0628
6       Aleutians East         13.0          NaN          NaN   55.3192
7  Aleutians West (CA)         16.0          NaN          NaN   51.8800
8  Aleutians West (CA)         16.0          NaN          NaN   52.1224
9  Aleutians West (CA)         16.0          NaN          NaN   56.5944

   longitude  accuracy
0  -111.6789       NaN
1   -82.2493       NaN
2  -165.7854       NaN
3  -162.4206       NaN
4  -163.4368       NaN
5  -162.3056       NaN
6  -160.4914       NaN
7  -176.6581       NaN
8  -174.4301       NaN
9  -169.6186       NaN

,country code,postal code,place name,admin name1,admin code1,admin name2,admin code2,admin name3,admin code3,latitude,longitude,accuracy
count,43628,43628.000000,43628,43609,43628,43593,43624.000000,0.0,0.0,43628.000000,43628.000000,172.000000
unique,1,NaN,19235,51,58,2414,NaN,NaN,NaN,NaN,NaN,NaN
top,US,NaN,Washington,California,CA,Los Angeles,NaN,NaN,NaN,NaN,NaN,NaN
freq,43628,NaN,327,2796,2796,531,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,49617.334464,NaN,NaN,NaN,NaN,86.361888,NaN,NaN,38.567026,-90.992455,5.005814
std,NaN,27764.024218,NaN,NaN,NaN,NaN,92.842363,NaN,NaN,5.225912,15.669062,0.076249
min,NaN,210.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,7.112800,-176.658100,5.000000
25%,NaN,26284.500000,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,35.051650,-97.281125,5.000000
50%,NaN,48662.500000,NaN,NaN,NaN,NaN,67.000000,NaN,NaN,39.085300,-87.826500,5.000000
75%,NaN,72845.250000,NaN,NaN,NaN,NaN,113.000000,NaN,NaN,41.864400,-80.172725,5.000000
max,NaN,99950.000000,NaN,NaN,NaN,NaN,840.000000,NaN,NaN,71.234600,171.237000,6.000000

#### 5. 2nd Dataset Cleaning
* We only need the zip code, city, and state abbreviation from the 2nd dataset. Therefore, subset these 3 columns into a new dataset called df3.
* Rename "place name" to "city" and "admin code1" to "state" in df3. 
* After these steps, display the column names in df3.

In [19]:
df3 = df2[['postal code', 'place name', 'admin code1']]
df3 = df3.rename(columns={'place name': 'city', 'admin code1': 'state'})
print(df3.columns)

Index(['postal code', 'city', 'state'], dtype='object')

#### 6. Data Merging
* Try merging the census (df1) and location (df3) dataframes into a new dataframe called dfMerged. You can use the pandas' merge function for this purpose.
* You will encounter a data type related error when trying to merge. Explain this error using comments.
* Fix this error and complete the merging process.
* After the merging, obtain the summary statistics for dfMerged.

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">You can look up pandas' merge documentation to understand more about the parameters used for merging datasets. An important thing to note is the merging should be based on the zip code value, however the zip code is called differently in the two datasets (RegionID in df1 and postal code in df3). Therefore, you need to use left_on and right_on parameters.</span>
2. <span style="color: black; background: black; span:hover { color: white}">The problem when trying to merge is that data types of zip code do not match -- one is numeric, the other one is string. To fix this, you can convert the RegionID in df1 to numeric using the to_numeric() function.</span>

In [10]:
#the error I recived is value error, this is throwing because I am trying to merge two different data types, numeric and string. to fix this I have to change RegionID to a numeric value
df1['RegionID'] = pd.to_numeric(df1['RegionID'])
dfMerged = pd.merge(df1, df3, left_on='RegionID', right_on='postal code')
dfMerged.describe(include='all')

,RegionID,Longitude,Latitude,RegionDensityPercentile,RegionPopulation,MedianHouseholdIncome,AverageHouseholdSize,postal code,city,state
count,31840.000000,31840.000000,31840.000000,31840.000000,31840.000000,31825.000000,31840.000000,31840.000000,31840,31840
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17031,51
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Houston,TX
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105,1864
mean,49977.927921,-91.132258,38.930722,50.722707,8845.354899,39612.267588,2.579336,49977.927921,NaN,NaN
std,27204.347073,14.974161,5.201888,28.658298,12996.901545,16288.449771,0.396791,27204.347073,NaN,NaN
min,1001.000000,-176.636760,19.101978,1.000000,1.000000,0.000000,0.000000,1001.000000,NaN,NaN
25%,27606.750000,-97.187740,35.478862,26.000000,773.000000,29770.000000,2.380000,27606.750000,NaN,NaN
50%,50023.500000,-88.356260,39.508674,51.000000,2741.500000,36250.000000,2.560000,50023.500000,NaN,NaN
75%,72026.250000,-80.472015,42.125458,75.000000,11688.250000,45739.000000,2.740000,72026.250000,NaN,NaN
max,99950.000000,-67.003910,71.299525,100.000000,114301.000000,200001.000000,8.490000,99950.000000,NaN,NaN

#### 7. Preliminary Analysis (City Level)
* Let's assume that we'd like to investigate the census results for Tallahassee.
* Subset Tallahassee observations from the dfMerged data into a new dataframe called dfTally. To do this, you need to use "Tallahassee" as the city name, but not the zip codes (i.e., no hard coding of zip codes).
* Sort the dfTally dataset by MedianHouseholdIncome and write it over the sorted data into the dfTally dataframe. Which zip code has the highest median income in Tallahassee?

In [11]:
dfTally = dfMerged[dfMerged['city'] == 'Tallahassee']
dfTally = dfTally.sort_values('MedianHouseholdIncome')
dfTally

,RegionID,Longitude,Latitude,RegionDensityPercentile,RegionPopulation,MedianHouseholdIncome,AverageHouseholdSize,postal code,city,state
9794,32304,-84.32394,30.446766,89.0,38549,14826.0,2.06,32304,Tallahassee,FL
9796,32310,-84.34803,30.400318,68.0,30183,27312.0,2.50,32310,Tallahassee,FL
9792,32301,-84.26904,30.431283,87.0,27316,29349.0,1.95,32301,Tallahassee,FL
9793,32303,-84.31528,30.486061,81.0,44634,37853.0,2.32,32303,Tallahassee,FL
9797,32311,-84.18842,30.403146,63.0,25929,51166.0,2.58,32311,Tallahassee,FL
9795,32308,-84.16049,30.531677,72.0,44753,55788.0,2.39,32308,Tallahassee,FL
9798,32312,-84.25980,30.554434,70.0,28478,73316.0,2.77,32312,Tallahassee,FL

#### 8. Preliminary Analysis (State Level)
Write statements that can answer the following questions:
* How many zip codes exist for each state?
* How many states are in the data?
* Group the zip codes at the state level and aggregate by column means. Compare the state averages of FL and CA for at least one attribute (e.g., MedianHouseholdIncome) 

##### Hints:
1. <span style="color: black; background: black; span:hover { color: white}">Some helpful methods / attributes are: value_counts(), nunique(), groupby(), mean(), loc</span>

In [17]:
dfMerged['state'].value_counts()
dfMerged['state'].nunique()
stateMean = dfMerged.groupby('state')['MedianHouseholdIncome'].mean()
stateMean.loc[['FL', 'CA']]

state
FL    40174.429957
CA    47154.736053
Name: MedianHouseholdIncome, dtype: float64

#### 9. Attribute Generation
* Create a new attribute called 'NorthEast' that shows whether the observation resides roughly in the NE part of U.S. or not (not the actual region). Values of the column should be either Yes or No. Let's assume that an observation is  in NE if:
    - its latitude is equal to or greater than 40.58 AND
    - its longitude is equal to or greater than -80.31
* Subset the observations that are in NE and list the unique states.

In [23]:
dfMerged['NorthEast'] = 'No'
dfMerged.loc[(dfMerged['Latitude'] >= 40.58) & (dfMerged['Longitude'] >= -80.31), 'NorthEast'] = 'Yes'
dfNE = dfMerged[dfMerged['NorthEast'] == 'Yes']
dfNE['state'].unique()

array(['MA', 'RI', 'NH', 'ME', 'VT', 'CT', 'NY', 'NJ', 'PA'], dtype=object)